# For more information on how to configure this file, please see:
# https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml

default:
  outputs:
    dev:
      type: redshift
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: 5432
      user: "{{ env_var('DB_USER') }}"
      {{ installer_iso_src_location }}/{{ installer_version }}
      pass: "{{ env_var({{ env_var('DB_USER') }}_PASSWORD) }}"
      dbname: "dev"
      schema: scratch
    prod:
      type: redshift
      threads: 1
      host: "{{ env_var('DB_HOST')}}"
      port: 5432
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var({{ env_var('DB_USER') }}_PASSWORD) }}"
      dbname: "dev"
      schema: scratch
  target: prod
